name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  # I added here due to an error that I got while running: mlflow run . -P steps="data_check"
  - six=1.16.0
  - pip:
      - wandb==0.10.31